spring:
  application:
    name: customer-service

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    encoder: json_v2

server:
  port: 8082

logging:
  level:
    org.springframework.cloud.sleuth: trace